### ISSUE TITLE
Add $ADEX to BSC token list

### ISSUE THREAD

**Issue by AlpineDex** [trustwallet/assets#15836] opened 2021-11-18 02:36 UTC
{
      "type": "BIP20",
      "address": "0x977b820f07b90d4a120B771b89B4cCD45187da91",
      "name": "Alpine Dex",
      "symbol": "ADEX",
      "decimals": 18,
      "logoURI": "https://www.instagram.com/p/CWWOecKLQ-e/?utm_medium=copy_link"
}

**Comment by cryptomanz** [comment] 2021-11-19 12:58
Duplicate of #15837

**Closed by cryptomanz** 2021-11-19 12:58 UTC
Labels: Type: New Feature

**Comment by AlpineDex** [comment] 2021-11-19 20:39
PINE and ADEX are not the same token but create by the same developers PINE is a reflection token and ADEX is a governance token both are unique
